### ISSUE TITLE
Dataset Format in folder dataset

### ISSUE THREAD

**Issue by henryzhao0615** [ycwu1997/D-Persona#2]
Hi,
According to the instruction, it said that ‘’‘ Put the data into "./dataset"  ’‘’ . However, May I ask what is the format of the dataset folder? Should it be something like:
for the path ./dataset
> ls
> MMIS2024TASK2_train MMIS2024TASK2_test MMIS2024TASK1

Or other kind of formats?

But If I tried: 
> cd MMIS2024TASK2_train
> ls
> Annotator_1.zip Annotator_2.zip Annotator_3.zip Annotator_4.zip

> cd MMIS2024TASK1
> ls
> training training_2d validation

How can I make the path correctly any instruction?

**Comment by ycwu1997** [comment]
Hello,
Due to the policy of our MMIS2024 challenge (now closed), the NPC170 dataset cannot be used directly in your work until it is officially released to the public. Please wait for further updates. The dataset is scheduled for public release next year, so it won't be a long wait. You can use the LIDC-IDRI to develop your solution first. Thank you for your understanding.
For the dataset format, it depends on the path you defined. Check the dataloader function for more details. See lines 25-31 https://github.com/ycwu1997/D-Persona/blob/main/D-Persona/code/dataloader/dataset.py

**Comment by ShiverK2727** [comment]
Hi @ycwu1997,

Thanks for the previous update about NPC170 dataset being released this year. Since we're now in mid-2025, I was wondering if there are any updates on the public release status? I'm eager to incorporate this dataset into my current research.

Best regards
